Traceback (most recent call last):
  File "pyg.py", line 22, in <module>
  File "runpy.pyc", line 240, in run_path
  File "runpy.pyc", line 82, in _run_module_code
  File "runpy.pyc", line 72, in _run_code
  File "main.py", line 4, in <module>
    from animation import Animation, PlayOnceAnimation
ImportError: No module named animation
Traceback (most recent call last):
  File "pyg.py", line 22, in <module>
  File "runpy.pyc", line 240, in run_path
  File "runpy.pyc", line 82, in _run_module_code
  File "runpy.pyc", line 72, in _run_code
  File "main.py", line 4, in <module>
    from animation import Animation, PlayOnceAnimation
ImportError: No module named animation
Traceback (most recent call last):
  File "pyg.py", line 22, in <module>
  File "runpy.pyc", line 240, in run_path
  File "runpy.pyc", line 82, in _run_module_code
  File "runpy.pyc", line 72, in _run_code
  File "main.py", line 4, in <module>
    from animation import Animation, PlayOnceAnimation
ImportError: No module named animation
Traceback (most recent call last):
  File "pyg.py", line 22, in <module>
  File "runpy.pyc", line 240, in run_path
  File "runpy.pyc", line 82, in _run_module_code
  File "runpy.pyc", line 72, in _run_code
  File "main.py", line 4, in <module>
    from animation import Animation, PlayOnceAnimation
ImportError: No module named animation
Traceback (most recent call last):
  File "pyg.py", line 22, in <module>
  File "runpy.pyc", line 240, in run_path
  File "runpy.pyc", line 82, in _run_module_code
  File "runpy.pyc", line 72, in _run_code
  File "main.py", line 4, in <module>
    from animation import Animation, PlayOnceAnimation
ImportError: No module named animation
